FROM ubuntu:14.04

ENV IS_DOCKER 1
RUN apt-get -y update
RUN apt-get install -y openssh-server python-pip python-dev git sudo
RUN pip install ansible
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir /var/run/sshd
RUN /usr/sbin/sshd -D &

EXPOSE 22
